# Generated by Django 3.2.8 on 2021-10-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberofduodecim',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Member of Duodecim'},
        ),
        migrations.AlterModelOptions(
            name='memberoffls',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Member of FLS'},
        ),
    ]
