# Generated by Django 3.2.8 on 2021-10-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20211005_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
