# Generated by Django 3.2.8 on 2021-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_spouse_date_of_marriage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
