# Generated by Django 3.2.8 on 2021-10-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_socialclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialclass',
            options={'ordering': ['-id'], 'verbose_name': 'Social Class', 'verbose_name_plural': 'Social Classes'},
        ),
    ]
