# Generated by Django 3.2.7 on 2021-10-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211005_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='member_of_FLS',
        ),
        migrations.RemoveField(
            model_name='person',
            name='member_of_duodecim',
        ),
    ]
