# Generated by Django 3.2.7 on 2021-09-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
