# Generated by Django 3.2.8 on 2021-10-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211005_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='retirement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
