# Generated by Django 3.2.8 on 2021-10-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_socialclass'),
        ('pages', '0004_person_retirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='social_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.socialclass'),
        ),
    ]
