# Generated by Django 3.2.8 on 2021-10-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docentship',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='docentship',
            name='end_date',
        ),
    ]
