# Generated by Django 3.2.7 on 2021-10-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='LicentiateOfPhilosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateOfPhilosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateOfMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.person')),
            ],
        ),
    ]
