# Generated by Django 3.2.7 on 2021-10-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateofmedicine',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='candidateofphilosophy',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='dispensation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='legislation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='licentiateofphilosophy',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='matriculation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='premedical',
            options={'ordering': ['-id']},
        ),
    ]
