# Generated by Django 3.2.8 on 2021-10-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_auto_20211005_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateofmedicine',
            options={'ordering': ['-id'], 'verbose_name': 'Candidate of Medicine', 'verbose_name_plural': 'Candidate of Medicine'},
        ),
        migrations.AlterModelOptions(
            name='candidateofphilosophy',
            options={'ordering': ['-id'], 'verbose_name': 'Candidate of Philosophy', 'verbose_name_plural': 'Candidate of Philosophy'},
        ),
        migrations.AlterModelOptions(
            name='dispensation',
            options={'ordering': ['-id'], 'verbose_name': 'Dispensation (women only)', 'verbose_name_plural': 'Dispensation (women only)'},
        ),
        migrations.AlterModelOptions(
            name='legislation',
            options={'ordering': ['-id'], 'verbose_name': 'Legislation', 'verbose_name_plural': 'Legislation'},
        ),
        migrations.AlterModelOptions(
            name='licentiateofphilosophy',
            options={'ordering': ['-id'], 'verbose_name': 'Licentiate of Medicine', 'verbose_name_plural': 'Licentiate of Medicine'},
        ),
        migrations.AlterModelOptions(
            name='matriculation',
            options={'ordering': ['-id'], 'verbose_name': 'Matriculation', 'verbose_name_plural': 'Matriculation'},
        ),
        migrations.AlterModelOptions(
            name='premedical',
            options={'ordering': ['-id'], 'verbose_name': 'Premedical', 'verbose_name_plural': 'Premedical'},
        ),
    ]
